name: Android EAS build (Preview)

on:
  workflow_dispatch:
    inputs:
      buildType:
        type: choice
        description: The build type
        options:
          - .apk
          - .aab

jobs:
  build:
    name: Create android preview build ${{ github.event.inputs.buildType }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.7.4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: pnpm install
      - name: Building .apk file
        if: ${{ github.event.inputs.buildType == '.apk' }}
        run: |
          eas build \
          --platform android \
          --profile preview \
          --message "${{ github.event.inputs.buildType }}" \
          --non-interactive
      - name: Building .aab file
        if: ${{ github.event.inputs.buildType == '.aab' }}
        run: |
          eas build \
          --platform android \
          --profile preview-playstore \
          --message "${{ github.event.inputs.buildType }}" \
          --non-interactive
