# I don't know why I bother creating this workflow
# since I don't have apple developer's account T_T

name: IOS EAS build

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options:
          - staging
          - production

jobs:
  build:
    name: Create ios preview build ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.7.4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: pnpm install
      - name: Build staging
        if: ${{ github.event.inputs.environment == 'staging' }}
        run: |
          eas build \
          --platform ios \
          --profile preview \
          --message "${{ github.event.inputs.environment }}" \
          --non-interactive
      - name: Build production
        if: ${{ github.event.inputs.environment == 'production' }}
        run: |
          eas build \
          --platform ios \
          --profile production \
          --message "${{ github.event.inputs.environment }}" \
          --non-interactive
